# Generated by Django 4.0.4 on 2022-08-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phoneno', models.PositiveBigIntegerField(unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=10, null=True)),
                ('orders', models.JSONField()),
                ('total', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.customer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='billing.sale')),
                ('mode', models.CharField(max_length=20)),
                ('gateway', models.CharField(max_length=20, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('pay_later_paid', models.PositiveIntegerField(blank=True, null=True)),
                ('pay_later_balance', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.customer_detail')),
            ],
        ),
    ]
