# Generated by Django 4.0.4 on 2022-08-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_gateway_alter_sale_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=40, unique=True)),
                ('iprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igst', models.DecimalField(decimal_places=2, max_digits=8)),
                ('istock', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isale', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
