# Generated by Django 4.0.4 on 2022-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_item_isale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='isale',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
